import { Routes,Route,Navigate } from 'react-router-dom'
import ProtectedRoute from './components/ProtectedRoute'; import AdminRoute from './components/AdminRoute'; import Layout from './components/Layout'
import Landing from './pages/Landing'; import Login from './pages/Login'; import Guide from './pages/Guide'; import Dashboard from './pages/Dashboard'; import Profile from './pages/Profile'; import MockList from './pages/MockList'; import MockInstruction from './pages/MockInstruction'; import TakeMock from './pages/TakeMock'; import Result from './pages/Result'; import Practice from './pages/Practice'; import PracticeSession from './pages/PracticeSession'; import Quota from './pages/Quota'
import AdminDashboard from './pages/admin/AdminDashboard'; import Students from './pages/admin/Students'; import StudentDetail from './pages/admin/StudentDetail'; import Questions from './pages/admin/Questions'; import ExamSets from './pages/admin/ExamSets'; import Analytics from './pages/admin/Analytics'

const Guard=({children,admin=false})=>admin?<AdminRoute><Layout admin>{children}</Layout></AdminRoute>:<ProtectedRoute><Layout>{children}</Layout></ProtectedRoute>
export default function App(){return <Routes>
 <Route path="/" element={<Landing/>}/><Route path="/login" element={<Login/>}/><Route path="/guide" element={<Guide/>}/>
 <Route path="/student/dashboard" element={<Guard><Dashboard/></Guard>}/><Route path="/student/profile" element={<Guard><Profile/></Guard>}/><Route path="/mock" element={<Guard><MockList/></Guard>}/><Route path="/mock/:examId/instruction" element={<Guard><MockInstruction/></Guard>}/><Route path="/mock/attempt/:attemptId" element={<ProtectedRoute><TakeMock/></ProtectedRoute>}/><Route path="/mock/result/:attemptId" element={<Guard><Result/></Guard>}/><Route path="/practice" element={<Guard><Practice/></Guard>}/><Route path="/practice/:subject" element={<Guard><PracticeSession/></Guard>}/><Route path="/quota" element={<Guard><Quota/></Guard>}/>
 <Route path="/admin" element={<Guard admin><AdminDashboard/></Guard>}/><Route path="/admin/students" element={<Guard admin><Students/></Guard>}/><Route path="/admin/students/:studentId" element={<Guard admin><StudentDetail/></Guard>}/><Route path="/admin/questions" element={<Guard admin><Questions/></Guard>}/><Route path="/admin/exam-sets" element={<Guard admin><ExamSets/></Guard>}/><Route path="/admin/analytics" element={<Guard admin><Analytics/></Guard>}/><Route path="*" element={<Navigate to="/" replace/>}/>
 </Routes>}
